apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-apihandson
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-apihandson
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 5