apiVersion: v1
kind: Pod
metadata:
  namespace: lab
  name: api-hands-k8s
  labels:
    app.project.name: api-hands-k8s
spec:
  containers:
    - name: hands-k8s
      image: cesarag92/handson-k8s
      ports:
        - containerPort: 5000
      env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"
  imagePullSecrets:
    - name: dockerhub-secret 
